version: '2.1'
executors:
  my:
    docker:
      - image: cimg/node:17.2.0
    working_directory: /mnt/ramdisk
    resource_class: medium

jobs:
  build:
    executor: my
    steps:
      - checkout
      - run: yarn --save
      - run: yarn test
    parallelism: 2

workflows:
  test:
    jobs:
      - build



