version: '2.1'
executors:
  my:
    docker:
      - image: cimg/node:17.2.0
    working_directory: /mnt/ramdisk
    resource_class: medium

jobs:
  test:
    parallelism: 2
    executor: my
    steps:
      - run: yarn --save
      - run: yarn test

workflows:
  test:
    jobs:
      - test



