version: '2.1'
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: yarn --save
  test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: yarn test

workflows:
  test:
    jobs:
      - build
      - test:
          requires:
            - build


